// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNq1PgJojGcOrJ7vnpRDYURIPs2mUzbcs',
    appId: '1:964438327357:web:14cdb59a0c945c91d22a54',
    messagingSenderId: '964438327357',
    projectId: 'prevailmart',
    authDomain: 'prevailmart.firebaseapp.com',
    storageBucket: 'prevailmart.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv3ga_42LiKJrvtu4v-hNY762q8KDzxKo',
    appId: '1:964438327357:android:abafe56b4a06e9c4d22a54',
    messagingSenderId: '964438327357',
    projectId: 'prevailmart',
    storageBucket: 'prevailmart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATzj3Kdd79lCGDhKFp6xWVS8tYlkSW4CY',
    appId: '1:964438327357:ios:69eb97c72afb4666d22a54',
    messagingSenderId: '964438327357',
    projectId: 'prevailmart',
    storageBucket: 'prevailmart.firebasestorage.app',
    iosBundleId: 'com.example.prevailmartApp',
  );
}
